namespace TechSupportRagBot.Services;

public static class UiText
{
    private static readonly Dictionary<string, string> En = new()
    {
        ["Access"] = "Access",
        ["Account"] = "Account",
        ["Activate"] = "Activate",
        ["ActivateKey"] = "Activate key",
        ["Add"] = "Add",
        ["AddToKnowledgeBase"] = "Issue solved, add the answer to knowledge base",
        ["Admin"] = "Administrator",
        ["Admins"] = "Administrators",
        ["Administration"] = "Administration",
        ["AllMachines"] = "All machines",
        ["AssignedTickets"] = "Assigned tickets",
        ["AssignOperators"] = "Assign",
        ["Avatar"] = "Avatar",
        ["AutoTranslate"] = "Auto-translate messages",
        ["AutoTranslateHelp"] = "When enabled, incoming messages from another country are translated after the chat opens.",
        ["AvailableMachines"] = "Available machines",
        ["Bot"] = "Bot",
        ["BotTyping"] = "Bot is typing",
        ["Categories"] = "Categories",
        ["Category"] = "Category",
        ["Changed"] = "changed",
        ["ChooseFile"] = "Choose file",
        ["Client"] = "Client",
        ["ClientAccounts"] = "Client accounts",
        ["ClientCabinet"] = "Client account",
        ["Clients"] = "Clients",
        ["CloseAndSave"] = "Close and save answer",
        ["CloseTicket"] = "Close ticket",
        ["Company"] = "Company",
        ["CompanyUsers"] = "Company users",
        ["Control"] = "Control",
        ["Country"] = "Country",
        ["CreateAdmin"] = "Create administrator",
        ["CreateClient"] = "Create client",
        ["CreateOperator"] = "Create operator",
        ["CreateTicket"] = "Create ticket",
        ["CreateUser"] = "Create user",
        ["Created"] = "Created",
        ["Dashboard"] = "Dashboard",
        ["Delete"] = "Delete",
        ["Documents"] = "Documents",
        ["Equipment"] = "Equipment",
        ["Female"] = "Female",
        ["File"] = "File",
        ["FinalAnswer"] = "Final answer",
        ["FullName"] = "Full name",
        ["Gender"] = "Gender",
        ["HeroEyebrow"] = "Local support line",
        ["HeroTitle"] = "Class-Engineering Suport",
        ["Home"] = "Home",
        ["IssuedPassword"] = "Issued password",
        ["Indexed"] = "Indexed",
        ["Key"] = "Key",
        ["KnowledgeBase"] = "Knowledge base",
        ["License"] = "License",
        ["LicenseActivation"] = "License activation",
        ["LicenseKey"] = "License key",
        ["Licenses"] = "Licenses",
        ["LineSupport"] = "Support line",
        ["Login"] = "Sign in",
        ["Logout"] = "Sign out",
        ["Machine"] = "Machine",
        ["MachineSupport"] = "Machine support",
        ["Machines"] = "Machines",
        ["Male"] = "Male",
        ["MyMachines"] = "My machines",
        ["MyTickets"] = "My tickets",
        ["NewAdmin"] = "New administrator",
        ["NewCategory"] = "New category",
        ["NewClient"] = "New client",
        ["NewCompanyUser"] = "New user",
        ["NewMessages"] = "New messages",
        ["NewQuestion"] = "New question",
        ["NotSpecified"] = "Not specified",
        ["NotIndexed"] = "Not added",
        ["Notifications"] = "Notifications",
        ["Open"] = "Open",
        ["OpenChat"] = "Open chat",
        ["OpenTickets"] = "Open tickets",
        ["Operator"] = "Operator",
        ["OperatorCard"] = "Operator card",
        ["OperatorTyping"] = "is typing",
        ["Operators"] = "Operators",
        ["Password"] = "Password",
        ["Phone"] = "Phone",
        ["Position"] = "Position",
        ["Profile"] = "Profile",
        ["Question"] = "Question",
        ["Queue"] = "Queue",
        ["RagLibrary"] = "RAG library",
        ["RecentTickets"] = "Recent tickets",
        ["RememberMe"] = "Remember me",
        ["Save"] = "Save",
        ["SelectCategory"] = "Select category",
        ["Send"] = "Send",
        ["Status"] = "Status",
        ["Subject"] = "Subject",
        ["Support"] = "Support",
        ["TakeToWork"] = "Take to work",
        ["Team"] = "Team",
        ["TemporaryPassword"] = "Temporary password",
        ["Tickets"] = "Tickets",
        ["Translation"] = "Translation",
        ["TranslationLoading"] = "Translation is loading...",
        ["UploadDocument"] = "Upload document",
        ["UploadIndex"] = "Upload and index",
        ["User"] = "User",
        ["Username"] = "Login",
        ["WriteMessage"] = "Write a message"
    };

    public static string T(HttpContext context, string key, string ru)
    {
        var lang = context.Request.Cookies["lang"];
        return lang == "en" && En.TryGetValue(key, out var value) ? value : ru;
    }

    public static string Status(HttpContext context, string status)
    {
        var lang = context.Request.Cookies["lang"];

        return status switch
        {
            Models.TicketStatuses.New => lang == "en" ? "New" : "Новый",
            Models.TicketStatuses.BotAnswered => lang == "en" ? "Bot answered" : "Ответ бота",
            Models.TicketStatuses.WaitingForOperator => lang == "en" ? "Waiting for operator" : "Ждет оператора",
            Models.TicketStatuses.InProgress => lang == "en" ? "In progress" : "В работе",
            Models.TicketStatuses.Closed => lang == "en" ? "Closed" : "Закрыт",
            _ => status
        };
    }
}
